<?php "ID" => $ID,
"block_ID" => $block_ID,

"BETA" => $BETA,
"user_id" => $user_id,
"your_rank" => $your_rank,
"sister_no" => $sister_no,
"brother_no" => $brother_no,
"mother_job" => $mother_job,
"nat2" => $nat2,
"edu_level2" => $edu_level2,
"mother_name" => $mother_name,
"edu_level1" => $edu_level1,
"one_family_mobile" => $one_family_mobile,
"one_family_name" => $one_family_name,
"email" => $email,
"mobile" => $mobile,
"revenue" => $revenue,

"addr_st" => $addr_st,
"addr_type" => $addr_type,
"addr_place" => $addr_place,
"city" => $city,

"zip_mail" => $zip_mail,
"post_mail" => $post_mail,
"home_no" => $home_no,
"certify_given_date" => $certify_given_date,
"dept" => $dept,
"certify" => $certify,
"firm_place" => $firm_place,
"firm_name" => $firm_name,
"edu_level" => $edu_level,
"job" => $job,
"ID_issue_place" => $ID_issue_place,
"ID_issue_date" => $ID_issue_date,
"ID_no" => $ID_no,
"ID_type" => $ID_type,
"face_color" => $face_color,
"unique_signal" => $unique_signal,
"blood" => $blood,
"marred" => $marred,
"gender" => $gender,
"nat" => $nat,

"birth_city" => $birth_city,
"birth_place" => $birth_place,
"birth_country" => $birth_country,
"birth" => $birth,

"raadbname" => $raadbname,
"image" => $image,
"tribe" => $tribe,
"name" => $name,

"c_at" => $c_at,
"u_at" => $u_at,
"st" => $st,